#!/bin/bash

# Purpose:	show difference between two runs of ip addr show
# Usage:	ip-addr-diff
# Example:	ip-addr-diff
# Responsible:	Stephan Rosenke <r01-571@r0s.de>
# License:	CC BY-SA 4.0
# Version:	2016-07-28

#set some user serviceable vars
diff="/usr/bin/diff"
diff_options="-u"
ip="/bin/ip"
ip_options="addr show"

################################################################################
# DO NOT MESS BEHIND THIS LINE #################################################
################################################################################

#set some non-user serviceable vars
scriptname=$(basename $0)
current="/var/log/${scriptname}_current"
old="/var/log/${scriptname}_old"

#functions
check_binary () {
 if [ ! -x "${1}" ] ; then
  echo "${1} does not exist ... exiting"
  exit 1
 fi
}
ip_current () {
 "${ip}" ${ip_options} >"${current}"
}

#check if binaries exist
for i in ${diff} ${ip} ; do
 check_binary "${i}"
done

#
#main
#

#check if $current exists otherwise touch it
test -e "${current}" || touch "${current}"
#check if $old exists, rm it
test -O "${old}" && rm "${old}"
#mv $current to $old
test -e "${old}" || mv "${current}" "${old}"

#dump netstat with current data
ip_current

#show differences
"${diff}" "${diff_options}" "${old}" "${current}"
